version: "3.9"

services:
  app:
    build: .
    container_name: domain-analyser
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/backend/data
    environment:
      UVICORN_WORKERS: "1"
    restart: unless-stopped
